apiVersion: v1
kind: ConfigMap
metadata:
  name: emulator-server-db-secret
  labels:
    app: emulator-server
data:
  POSTGRES_DB: quantum-emulator
  POSTGRES_USER: quantum-emulator
  POSTGRES_PASSWORD: quantum-emulator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emulator-server-sched-conf
  labels:
    app: emulator-server
data:
  qsched.json: |
    {
        "sched_min_gran": 200,
        "sched_min_depth": 10,
        "listen_ip": "0.0.0.0",
        "listen_port": 3000,
        "db_url": "postgres://quantum-emulator:quantum-emulator@localhost:5432/quantum-emulator",
        "agent_file": ""
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-server-db-pvc
  labels:
    app: emulator-server
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-server-log-pvc
  labels:
    app: emulator-server
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulator-server
  labels:
    app: emulator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emulator-server
  template:
    metadata:
      labels:
        app: emulator-server
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: emulator-server-db-secret
        volumeMounts:
        - name: emulator-server-pg-data
          mountPath: /var/lib/postgresql/data
      - name: emulator-server
        image: ghcr.io/baqic/emulate-server:main
        ports:
        - containerPort: 3000
        env:
        - name: QSCHED_CONFIG
          value: /config/qsched.json
        volumeMounts:
        - name: emulator-server-sched-conf-volume
          mountPath: /config
        - name: emulator-server-log-data
          mountPath: /log
      volumes:
      - name: emulator-server-sched-conf-volume
        configMap:
          name: emulator-server-sched-conf
      - name: emulator-server-pg-data
        persistentVolumeClaim:
          claimName: emulator-server-db-pvc
      - name: emulator-server-log-data
        persistentVolumeClaim:
          claimName: emulator-server-log-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: emulator-server-sv
  labels:
    app: emulator-server
spec:
  type: NodePort
  ports:
    - name: emulator-server 
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: emulator-server 