//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub use super::agent::Entity as Agent;
pub use super::options::Entity as Options;
pub use super::resource::Entity as Resource;
pub use super::task::Entity as Task;
