//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::physical_agent::Entity as PhysicalAgent;
pub use super::task::Entity as Task;
pub use super::task_active::Entity as TaskActive;
pub use super::task_assignment::Entity as TaskAssignment;
