apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.emulatorServerDb.storage.className}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.emulatorServerDb.storage.capacity}}