apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Release.Name }}
data:
  POSTGRES_DB: {{ .Values.emulatorServerDb.env.postgresDb }}
  POSTGRES_USER: {{ .Values.emulatorServerDb.env.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.emulatorServerDb.env.postgresPassword }}
