apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-sv-1
  labels:
    app: {{ .Release.Name }}-agent
spec:
  type: {{ .Values.emulatorServerAgent.service.type}}
  ports:
    - name: {{ .Values.emulatorServerAgent.service.ports.name}}
      port: {{ .Values.emulatorServerAgent.service.ports.port}}
      targetPort: {{ .Values.emulatorServerAgent.containerPort}}
  selector:
    app: {{ .Release.Name }}-agent