apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sv
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.emulatorServer.service.type}}
  ports:
    - name: {{ .Values.emulatorServer.service.ports.name}}
      port: {{ .Values.emulatorServer.service.ports.port}}
      targetPort: {{ .Values.emulatorServer.containerPort}}
      nodePort: {{ .Values.emulatorServer.service.ports.nodePort}}
  selector:
    app: {{ .Release.Name }}